name: Terraform GitHub Actions

on: 
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:

    - name: '"Configure AWS Credentials" Action for GitHub Actions'
      run: node20


    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.7.3

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform format
      id: fmt
      run: terraform fmt --recursive

    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: 1.7.3

    - name: Terraform init
      id: init
      run: terraform init
    
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve